# Copyright (c) 2009-2010 Satoshi Nakamoto
# Copyright (c) 2011-2024 The Version developers
# Distributed under the MIT/X11 software license, see the accompanying
# file license.txt or http://www.opensource.org/licenses/mit-license.php.

USE_UPNP:=0
USE_IPV6:=1

BDB_INCLUDE_PATH=/usr/local/include/db48
BDB_LIB_PATH=/usr/local/lib/db48

LINK:=$(CXX)

DEFS=-D__STDC_FORMAT_MACROS

DEFS += $(addprefix -I,$(CURDIR) $(CURDIR)/obj $(CURDIR)/univalue $(BDB_INCLUDE_PATH))
LIBS = $(addprefix -L,$(BDB_LIB_PATH))

LMODE = dynamic
LMODE2 = dynamic
ifdef STATIC
	LMODE = static
	ifeq (${STATIC}, all)
		LMODE2 = static
	endif
endif

LIBS += \
 -Wl,-B$(LMODE) \
   -l event \
   -l event_pthreads \
   -l db_cxx$(BDB_LIB_SUFFIX) \
   -l execinfo

ifndef USE_UPNP
	override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
	LIBS += -l miniupnpc
	DEFS += -DUSE_UPNP=$(USE_UPNP)
endif

ifneq (${USE_IPV6}, -)
	DEFS += -DUSE_IPV6=$(USE_IPV6)
endif

LIBS+= \
 -Wl,-B$(LMODE2) \
   -l z \
   -l pthread

# Hardening
# Make some classes of vulnerabilities unexploitable in case one is discovered.
#
    # This is a workaround for Ubuntu bug #691722, the default -fstack-protector causes
    # -fstack-protector-all to be ignored unless -fno-stack-protector is used first.
    # see: https://bugs.launchpad.net/ubuntu/+source/gcc-4.5/+bug/691722
    HARDENING=-fno-stack-protector

    # Stack Canaries
    # Put numbers at the beginning of each stack frame and check that they are the same.
    # If a stack buffer if overflowed, it writes over the canary number and then on return
    # when that number is checked, it won't be the same and the program will exit with
    # a "Stack smashing detected" error instead of being exploited.
    HARDENING+=-fstack-protector-all -Wstack-protector

    # Make some important things such as the global offset table read only as soon as
    # the dynamic linker is finished building it. This will prevent overwriting of addresses
    # which would later be jumped to.
    LDHARDENING+=-Wl,-z,relro -Wl,-z,now

    # Build position independent code to take advantage of Address Space Layout Randomization
    # offered by some kernels.
    # see doc/build-unix.txt for more information.
    ifdef PIE
        HARDENING+=-fPIE
        LDHARDENING+=-pie
    endif

    # -D_FORTIFY_SOURCE=2 does some checking for potentially exploitable code patterns in
    # the source such overflowing a statically defined buffer.
    HARDENING+=-D_FORTIFY_SOURCE=2
#

DEBUGFLAGS=-g

# CXXFLAGS can be specified on the make command line, so we use xCXXFLAGS that only
# adds some defaults in front. Unfortunately, CXXFLAGS=... $(CXXFLAGS) does not work.
xCXXFLAGS=-O0 -msse2 -pthread -std=c++17 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter \
    $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(CXXFLAGS)

# LDFLAGS can be specified on the make command line, so we use xLDFLAGS that only
# adds some defaults in front. Unfortunately, LDFLAGS=... $(LDFLAGS) does not work.
xLDFLAGS=$(LDHARDENING) $(LDFLAGS)

OBJS= \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/httpserver.o \
    obj/httprpc.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/cleanse.o \
    obj/crypter.o \
    obj/key.o \
    obj/pubkey.o \
    obj/txdb.o \
    obj/db.o \
    obj/init.o \
    obj/keystore.o \
    obj/main.o \
    obj/miner.o \
    obj/net.o \
    obj/protocol.o \
    obj/rpcserver.o \
    obj/rpcprotocol.o \
    obj/rpcclient.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/base58.o \
    obj/script.o \
    obj/sync.o \
    obj/random.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/kernel.o \
    obj/crypto/aes.o \
    obj/crypto/sha256.o \
    obj/crypto/hmac_sha256.o \
    obj/crypto/sha512.o \
    obj/crypto/ripemd160.o \
    obj/crypto/sha1.o \
    obj/univalue/univalue.o \
    obj/univalue/univalue_get.o \
    obj/univalue/univalue_read.o \
    obj/univalue/univalue_write.o \
    obj/sqlite3/sqlite3.o

all: versiond

# build secp256k1
DEFS += $(addprefix -I,$(CURDIR)/secp256k1/include)
LIBS += $(CURDIR)/secp256k1/.libs/libsecp256k1.a

SECP256K1_SRC := $(shell find secp256k1/src secp256k1/include -type f \( -name '*.c' -o -name '*.h' \) 2>/dev/null) \
                  secp256k1/configure.ac secp256k1/Makefile.am

secp256k1/.libs/libsecp256k1.a: $(SECP256K1_SRC)
	@echo "Building Secp256k1 ..."; \
	cd secp256k1; \
	chmod 755 *; \
	./autogen.sh; \
	./configure --disable-shared --with-pic --enable-benchmark=no --enable-tests=no --enable-exhaustive-tests=no --enable-module-recovery --enable-module-schnorrsig --enable-experimental; \
	$(MAKE); \
	cd ..

versiond: secp256k1/.libs/libsecp256k1.a

# build leveldb
LIBS += $(CURDIR)/leveldb/out-static/libleveldb.a $(CURDIR)/leveldb/out-static/libmemenv.a
DEFS += $(addprefix -I,$(CURDIR)/leveldb/include)
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
leveldb/out-static/libleveldb.a:
	@echo "Building LevelDB ..."; cd leveldb; gmake out-static/libleveldb.a out-static/libmemenv.a; cd ..;
obj/txdb.o: leveldb/out-static/libleveldb.a

# auto-generated dependencies:
-include obj/*.P

obj/build.h: FORCE
	/bin/sh ../share/genbuild.sh obj/build.h
version.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

SQLITE_CFLAGS = -DSQLITE_THREADSAFE=1 -DSQLITE_OMIT_LOAD_EXTENSION -Wno-discarded-qualifiers
obj/sqlite3/sqlite3.o: sqlite3/sqlite3.c
	$(CC) -c -O2 $(SQLITE_CFLAGS) -I$(CURDIR)/sqlite3 -MMD -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

versiond: $(OBJS:obj/%=obj/%)
	$(CXX) $(xCXXFLAGS) -rdynamic -o $@ $^ $(LDFLAGS) $(LIBS)

TESTOBJS := $(patsubst test/%.cpp,obj-test/%.o,$(wildcard test/*.cpp))

obj-test/%.o: test/%.cpp
	$(CXX) -c $(TESTDEFS) $(xCXXFLAGS) -MMD -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

test_version: $(TESTOBJS) $(filter-out obj/init.o,$(OBJS:obj/%=obj/%))
	$(CXX) $(xCXXFLAGS) -o $@ $(LIBPATHS) $^ -Wl,-B$(LMODE) $(LDFLAGS) $(LIBS)

clean:
	-rm -f versiond test_version
	-rm -f obj/*.o
	-rm -f obj-test/*.o
	-rm -f obj/*.P
	-rm -f obj-test/*.P
	-rm -f src/build.h

FORCE:
